<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit4c40efde52a770b0aa3adf715ce1f568
{
    public static $prefixLengthsPsr4 = array (
        'I' => 
        array (
            'Ifsnop\\' => 7,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Ifsnop\\' => 
        array (
            0 => __DIR__ . '/..' . '/ifsnop/mysqldump-php/src/Ifsnop',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit4c40efde52a770b0aa3adf715ce1f568::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit4c40efde52a770b0aa3adf715ce1f568::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
